Nombre y apellidos: Alfonso Íñiguez Cortés \
Correo: aic35@alu.ua.es \
Grupo: 3 

# BFS. Exploración de grafos

In [1]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, Markdown 

Implementación del algoritmo BFS:

In [1]:
def dfs_numpy(graph, source, target):
    nodes = list(graph.nodes())
    adjacency_matrix = nx.to_numpy_array(graph, nodelist=nodes)

    visited = np.zeros(len(nodes), dtype=bool)
    source_index = nodes.index(source)
    target_index = nodes.index(target)
    visited[source_index] = True

    to_explore = [source_index]
    current_position = len(to_explore) - 1  # DFS: always the last element

    parent = np.ones(len(nodes), dtype=int) * -1
    steps = 0

    while len(to_explore) > 0:
        steps += 1
        current_index = to_explore[current_position]
        to_explore.pop(current_position)

        if current_index == target_index:
            break

        neighbors = np.where(adjacency_matrix[current_index] == 1)[0]
        for neighbor_index in neighbors:
            if not visited[neighbor_index]:
                visited[neighbor_index] = True
                to_explore.append(neighbor_index)
                current_position = len(to_explore) - 1
                parent[neighbor_index] = current_index

        if len(to_explore) > 0:
            current_position = len(to_explore) - 1

    path = []
    if parent[target_index] != -1 or source_index == target_index:
        current = target_index
        while current != -1:
            path.insert(0, nodes[current])
            current = parent[current]

    return steps, path

## Ejercicios

### Ejercicio 2

El algoritmo DFS és, al igual que BFS, un algoritmo de exploración de grafos. BFS es un algoritmo que recorre los grafos en anchura, sim embargo DFS los explora por profundidad. Este algoritmo no recorre el algoritmo por niveles, si no que explora caminos completamente. Es decir, selecciona un vecino y recorre todos sus vecinos hasta pasar al siguiente. Este algoritmo no asegura el camino más óptimo, pero puede encontrar un camino válido en menos pasos y con menos coste que BFS. En general, esto algoritmo es muy útil cuando se tiene que encontrar un camino en el menor tiempo posible y sin que importe si este es el más óptimo. 

Implementación DFS (ejecución paso a paso):

In [8]:
def dfs_numpy(graph, source, target):

    display(Markdown('## Recorriendo el algoritmo con DFS'))
    display(Markdown('---'))

    # Listamos los nodos del grafo a explorar
    nodes = list(graph.nodes())
    display(Markdown('#### Datos iniciales'))
    display(Markdown(f'**Lista de nodos del grafo:** {nodes}'))

    # Obtenemos la matriz de adyacencia del grafo
    adjacency_matrix = nx.to_numpy_array(graph, nodelist=nodes)
    display(Markdown(f'**Matriz de adyacencia:**'))
    print(adjacency_matrix)

    # Array (booleano) para guardar los nodos ya visitados
    visited = np.zeros(len(nodes), dtype=bool)

    # Posición del nodo origen (dentro de la lista 'nodes')
    source_index = nodes.index(source)

    # Posición del nodo destino (dentro de la lista 'nodes')
    target_index = nodes.index(target)

    display(Markdown(f'**Nodo origen:** {source} (índice {source_index}) | **Nodo destino:** {target} (índice {target_index})'))

    # El nodo desde donde partimos marcado como visitado
    visited[source_index] = True

    # Lista de nodos pendientes de explorar, empezamos con el origen
    to_explore = [source_index]

    # Puntero al último elemento de la lista (DFS explora en profundidad, no por niveles)
    current_position = len(to_explore) - 1

    # Array para guardar de qué nodo venimos, usado para la reconstrucción del camino
    parent = np.ones(len(nodes), dtype=int) * -1

    # Número de pasos
    steps = 0

    display(Markdown('---'))
    display(Markdown(f'#### Comenzando exploración desde el nodo {source}...'))

    while len(to_explore) > 0:
        steps += 1
        current_index = to_explore[current_position]
        to_explore.pop(current_position)

        display(Markdown('---'))
        display(Markdown(f'**Paso {steps}** | Nodo actual: `{nodes[current_index]}`'))

        if current_index == target_index:
            display(Markdown(f'**Destino encontrado: {target}**'))
            break

        # Vecinos del nodo actual
        neighbors = np.where(adjacency_matrix[current_index] == 1)[0]
        display(Markdown(f'Vecinos de `{nodes[current_index]}`: {[nodes[i] for i in neighbors]}'))

        # Recorremos los vecinos del nodo actual y exploramos en profundidad
        for neighbor_index in neighbors:
            if not visited[neighbor_index]:
                visited[neighbor_index] = True
                to_explore.append(neighbor_index)
                current_position = len(to_explore) - 1
                parent[neighbor_index] = current_index
                display(Markdown(f'Añadimos a la lista: `{nodes[neighbor_index]}`'))

        if len(to_explore) > 0:
            current_position = len(to_explore) - 1
            display(Markdown(f'*Siguiente nodo a explorar (el más profundo disponible): `{nodes[to_explore[current_position]]}`*'))

    path = []
    if parent[target_index] != -1 or source_index == target_index:
        current = target_index
        while current != -1:
            path.insert(0, nodes[current])
            current = parent[current]

    display(Markdown('---'))
    display(Markdown('#### Resultado'))
    display(Markdown(f'**Camino encontrado:** {path}'))
    display(Markdown(f'**Número de pasos:** {steps}'))

    return steps, path

### Ejercicio 2

#### Primer grafo

In [1]:
# Creamos 4 bloques de 10 nodos cada uno
sizes = [10, 10, 10, 10]

# Definimos las matrices de probabilidad:
    # Baja: Probabilidad baja conexión entre bloques distintos
baja = [
    [0.8, 0.02, 0.02, 0.02],
    [0.02, 0.8, 0.02, 0.02],
    [0.02, 0.02, 0.8, 0.02],
    [0.02, 0.02, 0.02, 0.8]
]
# Definimos la semilla para que los resultados sean reproducibles
seed = 96

# Creamos los 2 grafos (SBM)
G1 = nx.stochastic_block_model(sizes, baja, seed=seed)  # El primero -> Probabilidad alta

# Calculamos las posiciones (las mismas para los dos grafos)
pos = nx.spring_layout(G1, seed=seed)


# Primer grafo
#--------------#
# Definimos título
plt.title('SBM - Baja conexion entre bloques')  
nx.draw_networkx_nodes(G1, pos1, node_size=300, node_color='green')  # Dibujamos los nodos
nx.draw_networkx_edges(G1, pos1, width=1.0, alpha=0.5, edge_color='black', style='-.') # Dibujamos las aristas
plt.axis('off')

# Mostramos el resultado por pantalla
plt.show()

NameError: name 'nx' is not defined

**Probamos el algoritmo:**

In [11]:
dfs_numpy(G1, source = 3, target = 37)

## Recorriendo el algoritmo con DFS

---

#### Datos iniciales

**Lista de nodos del grafo:** [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 32, 33, 34, 35, 36, 37, 38, 39, 30, 31]

**Matriz de adyacencia:**

[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 1. 0.]]


**Nodo origen:** 3 (índice 3) | **Nodo destino:** 37 (índice 35)

---

#### Comenzando exploración desde el nodo 3...

---

**Paso 1** | Nodo actual: `3`

Vecinos de `3`: [0, 1, 2, 4, 5, 6, 7, 9, 39, 31]

Añadimos a la lista: `0`

Añadimos a la lista: `1`

Añadimos a la lista: `2`

Añadimos a la lista: `4`

Añadimos a la lista: `5`

Añadimos a la lista: `6`

Añadimos a la lista: `7`

Añadimos a la lista: `9`

Añadimos a la lista: `39`

Añadimos a la lista: `31`

*Siguiente nodo a explorar (el más profundo disponible): `31`*

---

**Paso 2** | Nodo actual: `31`

Vecinos de `31`: [3, 23, 32, 35, 36, 37, 38, 39, 30]

Añadimos a la lista: `23`

Añadimos a la lista: `32`

Añadimos a la lista: `35`

Añadimos a la lista: `36`

Añadimos a la lista: `37`

Añadimos a la lista: `38`

Añadimos a la lista: `30`

*Siguiente nodo a explorar (el más profundo disponible): `30`*

---

**Paso 3** | Nodo actual: `30`

Vecinos de `30`: [32, 33, 34, 35, 36, 37, 38, 39, 31]

Añadimos a la lista: `33`

Añadimos a la lista: `34`

*Siguiente nodo a explorar (el más profundo disponible): `34`*

---

**Paso 4** | Nodo actual: `34`

Vecinos de `34`: [32, 33, 36, 38, 39, 30]

*Siguiente nodo a explorar (el más profundo disponible): `33`*

---

**Paso 5** | Nodo actual: `33`

Vecinos de `33`: [32, 34, 35, 36, 37, 39, 30]

*Siguiente nodo a explorar (el más profundo disponible): `38`*

---

**Paso 6** | Nodo actual: `38`

Vecinos de `38`: [34, 35, 36, 37, 39, 30, 31]

*Siguiente nodo a explorar (el más profundo disponible): `37`*

---

**Paso 7** | Nodo actual: `37`

**Destino encontrado: 37**

---

#### Resultado

**Camino encontrado:** [3, 31, 37]

**Número de pasos:** 7

(7, [3, 31, 37])

#### Segundo grafo

In [2]:
# Creamos 4 bloques de 10 nodos cada uno
sizes = [10, 10, 10, 10]

# Definimos las matrices de probabilidad:
    # Alta: Probabilidad alta conexión entre bloques distintos
alta = [
    [0.8, 0.8, 0.8, 0.8],
    [0.8, 0.8, 0.8, 0.8],
    [0.8, 0.8, 0.8, 0.8],
    [0.8, 0.8, 0.8, 0.8]
]
# Definimos la semilla para que los resultados sean reproducibles
seed = 96

# Creamos los 2 grafos (SBM)
G2 = nx.stochastic_block_model(sizes, alta, seed=seed)  # El segundo -> Probabilidad baja


# Segundo grafo
#---------------#
# Definimos título
plt.title('SBM - Alta conexion entre bloques')
nx.draw_networkx_nodes(G2, pos, node_size=300, node_color= 'yellow')         # Dibujamos los nodos
nx.draw_networkx_edges(G2, pos, width=1.0, alpha=0.5, style=':')  # Dibujamos las arsitas
plt.axis('off')

# Mostramos el resultado por pantalla
plt.show()

NameError: name 'nx' is not defined

**Probamos el algoritmo:**

In [12]:
dfs_numpy(G2, source = 1, target = 38)

## Recorriendo el algoritmo con DFS

---

#### Datos iniciales

**Lista de nodos del grafo:** [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 32, 33, 34, 35, 36, 37, 38, 39, 30, 31]

**Matriz de adyacencia:**

[[0. 1. 0. ... 0. 1. 1.]
 [1. 0. 1. ... 1. 1. 0.]
 [0. 1. 0. ... 0. 1. 1.]
 ...
 [0. 1. 0. ... 0. 1. 1.]
 [1. 1. 1. ... 1. 0. 1.]
 [1. 0. 1. ... 1. 1. 0.]]


**Nodo origen:** 1 (índice 1) | **Nodo destino:** 38 (índice 36)

---

#### Comenzando exploración desde el nodo 1...

---

**Paso 1** | Nodo actual: `1`

Vecinos de `1`: [0, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 15, 16, 17, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 33, 34, 35, 36, 38, 39, 30]

Añadimos a la lista: `0`

Añadimos a la lista: `2`

Añadimos a la lista: `3`

Añadimos a la lista: `4`

Añadimos a la lista: `5`

Añadimos a la lista: `6`

Añadimos a la lista: `7`

Añadimos a la lista: `8`

Añadimos a la lista: `10`

Añadimos a la lista: `11`

Añadimos a la lista: `12`

Añadimos a la lista: `13`

Añadimos a la lista: `15`

Añadimos a la lista: `16`

Añadimos a la lista: `17`

Añadimos a la lista: `19`

Añadimos a la lista: `20`

Añadimos a la lista: `21`

Añadimos a la lista: `22`

Añadimos a la lista: `23`

Añadimos a la lista: `25`

Añadimos a la lista: `26`

Añadimos a la lista: `27`

Añadimos a la lista: `28`

Añadimos a la lista: `29`

Añadimos a la lista: `33`

Añadimos a la lista: `34`

Añadimos a la lista: `35`

Añadimos a la lista: `36`

Añadimos a la lista: `38`

Añadimos a la lista: `39`

Añadimos a la lista: `30`

*Siguiente nodo a explorar (el más profundo disponible): `30`*

---

**Paso 2** | Nodo actual: `30`

Vecinos de `30`: [0, 1, 2, 4, 5, 7, 9, 10, 11, 12, 15, 16, 17, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 32, 33, 34, 35, 36, 37, 38, 39, 31]

Añadimos a la lista: `9`

Añadimos a la lista: `24`

Añadimos a la lista: `32`

Añadimos a la lista: `37`

Añadimos a la lista: `31`

*Siguiente nodo a explorar (el más profundo disponible): `31`*

---

**Paso 3** | Nodo actual: `31`

Vecinos de `31`: [0, 2, 3, 4, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25, 27, 28, 29, 32, 34, 35, 36, 37, 38, 39, 30]

Añadimos a la lista: `14`

Añadimos a la lista: `18`

*Siguiente nodo a explorar (el más profundo disponible): `18`*

---

**Paso 4** | Nodo actual: `18`

Vecinos de `18`: [0, 2, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 22, 25, 26, 27, 28, 29, 32, 33, 35, 36, 37, 39, 31]

*Siguiente nodo a explorar (el más profundo disponible): `14`*

---

**Paso 5** | Nodo actual: `14`

Vecinos de `14`: [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 32, 33, 34, 37, 39, 31]

*Siguiente nodo a explorar (el más profundo disponible): `37`*

---

**Paso 6** | Nodo actual: `37`

Vecinos de `37`: [0, 2, 6, 7, 12, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 27, 29, 32, 33, 34, 35, 36, 38, 39, 30, 31]

*Siguiente nodo a explorar (el más profundo disponible): `32`*

---

**Paso 7** | Nodo actual: `32`

Vecinos de `32`: [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 26, 27, 28, 29, 33, 34, 35, 36, 37, 38, 30, 31]

*Siguiente nodo a explorar (el más profundo disponible): `24`*

---

**Paso 8** | Nodo actual: `24`

Vecinos de `24`: [0, 2, 3, 5, 6, 7, 8, 9, 10, 14, 16, 17, 20, 21, 22, 23, 25, 27, 28, 29, 32, 33, 34, 35, 36, 37, 38, 39, 30, 31]

*Siguiente nodo a explorar (el más profundo disponible): `9`*

---

**Paso 9** | Nodo actual: `9`

Vecinos de `9`: [0, 2, 3, 5, 6, 7, 10, 11, 12, 13, 14, 16, 17, 18, 20, 21, 22, 23, 24, 26, 27, 28, 29, 32, 33, 34, 35, 36, 38, 39, 30, 31]

*Siguiente nodo a explorar (el más profundo disponible): `39`*

---

**Paso 10** | Nodo actual: `39`

Vecinos de `39`: [1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 27, 28, 29, 33, 34, 35, 36, 37, 30, 31]

*Siguiente nodo a explorar (el más profundo disponible): `38`*

---

**Paso 11** | Nodo actual: `38`

**Destino encontrado: 38**

---

#### Resultado

**Camino encontrado:** [1, 38]

**Número de pasos:** 11

(11, [1, 38])

### Resultados y conclusión

&rarr; **completar**