Nombre y apellidos = Alfonso Íñiguez Cortés \
gmail: aic35@alu.ua.es \
Grupo: 3

## NetworkX

`NetworkX` es una librería que nos permite trabajar en grafos...

## 1. Instalación

Para empezar, vamos a instalar e importar `NetworkX` para poder trabajar con ella el resto del cuaderno:

In [28]:
try:
    !pip install networkx
    !pip show networkx
except:
    f"No se ha podido descargar la librería"

Name: networkx
Version: 3.2.1
Summary: Python package for creating and manipulating graphs and networks
Home-page: 
Author: 
Author-email: Aric Hagberg <hagberg@lanl.gov>
License: 
Location: /opt/miniconda3/envs/discrete_brain/lib/python3.9/site-packages
Requires: 
Required-by: torch


## 2. Importación de paquetes

Una vez instalada, vamos a importarla para usarla en nuestro código:

In [29]:
import networkx as nx

## 3. Creación de un grafo

Vamos a crear nuestro primer grafo usando esta librería. Para ello, tenemos la función ``Graph()``. Vamos a poner un ejemplo de ello creando un grafo vacío:

In [30]:
grafo = nx.Graph()
print(grafo)

Graph with 0 nodes and 0 edges


El anterior grafo era uno no dirigido, pero `NetworkX` nos ofrece una función para crear grafos dirigidos. Vamos a explicar antes la diferencia entre ambos tipos de grafos:

- Grafo dirigido -> Utilizan flechas para indicar una dirección específica en sus aristas (unidireccionales)
- Grafo NO dirigido -> Utilizan lineas simples que representan relaciones bidireccionales. 

La función que usamos para crear grafos dirigido, usamos `DiGraph()`. Vamos a poner un ejemplo creando un grafo vacío:

In [31]:
grafo_dirigido = nx.DiGraph()
print(grafo)

Graph with 0 nodes and 0 edges


### 3.1 Creación de un grafo a partir de una matriz Numpy 

De momento solo hemos creando grafos vacíos, el siguiente paso es crearlos con datos. En este apartado vamos a crear un grafo a partir de una matriz numpy. Para ello, usamos nuevamente las funciones básicas: `Graph()` y `DiGraph()`. Vamos a crear un ejemplo de como crear un grafo dirigido y no dirigido usando una matriz Numpy:

In [32]:
import numpy as np

matriz_numpy = np.array([[1,0],[1,1]])
grafo = nx.Graph(matriz_numpy)
print(grafo)
print(grafo.nodes)
print(grafo.edges)

Graph with 2 nodes and 3 edges
[0, 1]
[(0, 0), (0, 1), (1, 1)]


Notamos como hemos creado un grafo con 2 nodos y dos aristas. El funcionamiento es el siguiente:

```python
matriz_numpy = np.array([[1,0],[0,1]])
grafo = nx.Graph(matriz_numpy)
```
Vamos a explicar como se crea este grafo a partir de esos datos. Cuando usamos una array de numpy, tenemos esto : [1,0] y [1,1]. Esos dos elementos son los nodos. Por eso nos dice que hemos creando un grafo `with 2 nodes`. Ahora que sabemos donde se definen los nodos, vamos a explicar de donde salen las aristas. Para entenderlo bien, vamos a fijranos en los nodos:

- Nodo "0": [1,0] -> De este nodo, va a salir una arista puedo que tenemos un 1. Para ser más precisos, esta arista (edge) es la (0,0), puesto que el 1 esta en el nodo "0" y dentro de este nodo esta en la posición "0". 
- Nodo "1": De que obtenemos 2 aristas, puesto que hay dos "1". Estos se encuentran en el nodo "1" y en las posiciones "0" y "1", por eso obtenemos las aristas (0,1) y (1,1).

Un apunte más para entender la distinción entre grafos dirigidos y no dirigidos es la arista (0,1). Recordamos que está en el nodo "1" y en la posición "0", entonces: ¿Por qué no es (1,0) y es (0,1)? Esto sería así si se tratara de un grafo dirigido, pero al tratarse de un grafo no dirigido las aristas tienen sentido bidireccional y se representa como (0,1).

Vamos a crear ahora un ejemplo de un grafo dirigido usando una matirz numpy para notar esta distinción:

In [33]:
import numpy as np

matriz_numpy = np.array([[1,0],[1,1]])
grafo = nx.DiGraph(matriz_numpy)
print(grafo)
print(grafo.nodes)
print(grafo.edges)

DiGraph with 2 nodes and 3 edges
[0, 1]
[(0, 0), (1, 0), (1, 1)]


Notamos como ahora sí tenemos la aristas como (1,0) y no como (0,1). Para obtener las aristas y nodos de un grafo usamos las funciones:

- .nodes: Devuelve los nodos
- .edges: Devuelve las aristas

Otra función que podemos usar es `nx.adjacency_matrix()` junto con `todense()`, que realizan respectivamente: devuelve la matriz de adyacencia de un grafo (formato matriz dispersa) y convierte una matriz dispersa a matriz densa. Vamos a ver el funcionamiento:

In [34]:
print('Matriz de adyacencia del grafo:')
print(nx.adjacency_matrix(grafo))
print('Matriz densa:')
print(nx.adjacency_matrix(grafo).todense())

Matriz de adyacencia del grafo:
  (0, 0)	1
  (1, 0)	1
  (1, 1)	1
Matriz densa:
[[1 0]
 [1 1]]


### 3.2 Creación de un grafo a partir de un DataFrame de Pandas

Otra forma de cración de grafos es usando un DataFrame. Vamos a poner un ejemplo :

In [44]:
import pandas as pd

df = pd.DataFrame({'from': [0, 1, 2, 3], 'to': [1, 0, 3, 2]}) 
grafo = nx.from_pandas_edgelist(df, 'from', 'to') 
print(grafo)
print(grafo.nodes) 
print(grafo.edges) 

Graph with 4 nodes and 2 edges
[0, 1, 2, 3]
[(0, 1), (2, 3)]


El funcionamiento es el siguiente:

Creamos el DataFrame usando un diccionario que contiene 2 claves: `from` y `to`:
- from -> Definimos los nodos (en este caso creamos 4 nodos que son el 0, el 1...)
- to -> Definimos las conexiones entre los nodos (aristas): Tenemos dos listas, en la primera tenemos los nodos y en la segunda a que nodos se conectan los originales. Las conexiones de definen por la posición, es decir, en nuestro ejemplo tenemos:

```python
nodos: list = [0,1,2,3]
nodos_a_los_que_se_conectan_los_nodos: list = [1,0,3,2]
```

Tenemos que el nodo "0" se conceta con el nodo "1" (ambos estan en la primera posición)
Luego el nodo "1" se conecta con el "0" (como esta arista ya estaba definida (0,1), no se guarda)
Luego tenemos que el nodo "2" se conceta con el nodo "3" (dando luegar a la arista (2,3))

Y así sucesivamente se van definiendo los nodos y las aristas.

In [45]:
print('Conexiones')
print(nx.adjacency_matrix(grafo).todense())

Conexiones
[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]


Vamos a explicar la matriz de adyacencia con mayor claridad: ...

### 3.3 Adición de nodos

`NetworkX` nos ofrece la función `add_nodes()`, la cual nos permite insertar a nuestro grafo un nodo. Recibe como parámetro el índice del nodo que queramos añadir. Para poder añadir varios nodos a la vez, tenemos la función `add_nodes_from([])` que recibe los índices (dentro de una lista) de los nodos a instertar. Vamos a crear un grafo vacío y luego vamos a añadir nodos a modo de ejemplo:

In [53]:
# Creación grafo vacío
grafo = nx.Graph() # Lo hacemos no dirigido
print(f'Grafo vacío: \n{grafo}\n')
# Añadimos un nodo
grafo.add_node(1)  # Añadimos el nodo con el índice "1"
print(f'Grafo después de la inserción: \n{grafo} | Nodos->  {grafo.nodes} | Aristas-> {grafo.edges}\n')

# Podemos añadir varios nodos a la vez
grafo.add_nodes_from([10,11,12,13])
print(f'Grafo después de la inserción de varios nodos: \n{grafo} | Nodos->  {grafo.nodes} | Aristas-> {grafo.edges}')

Grafo vacío: 
Graph with 0 nodes and 0 edges

Grafo después de la inserción: 
Graph with 1 nodes and 0 edges | Nodos->  [1] | Aristas-> []

Grafo después de la inserción de varios nodos: 
Graph with 5 nodes and 0 edges | Nodos->  [1, 10, 11, 12, 13] | Aristas-> []


A la hora de añadir nodos, podemos crearlos con atributos.  
### completar

### 3.4 Adición de aristas

Ahora que hemos visto como agregar nodos...

#### ejemplo clase

In [36]:
from pandas import DataFrame

df = DataFrame
G = nx.Graph()

for i, fila in df.iterrows():
    G.add_node(i) # 0,1,2,3 
    for j in fila["Conections"]:
        G.add_edge(i,j)

nx.draw(G, with_labels=True)
plt.show()

TypeError: iterrows() missing 1 required positional argument: 'self'