Nombre y apellidos: Alfonso Íñiguez Cortés \
gmail: aic35@alu.ua.es \
Grupo: 3

## EJERCICIO 2 
### IMPLEMENTACIÓN DE LA CALCULADORA DE MATRIZ NUMPY

In [ ]:
import numpy as np


#main
def array_calculator(array1: np.ndarray, array2: np.ndarray, operation: str) -> np.ndarray:

    if operation == '+':
        return sumar(array1, array2)
    elif operation == '-':
        return restar(array1, array2)
    elif operation == '*':
        return multiplicar(array1, array2)
    elif operation == 'concat':
        return concatenar(array1, array2)
    elif operation == 'transpose':
        return transponer(array1)

    else:
        return f'Operación no válida'
    

#auxiilares
def sumar(a, b):
    if a.shape != b.shape:
        return 'Las matrices deben tener las misms dimensiones para sumarlas'
    return a + b

def restar(a, b):
    if a.shape != b.shape:
        return f'Las matrices deben tener las mismas dimenensiones para que se resten'
    return a - b

def multiplicar(a, b):
    if a.shape[1] != b.shape[0]:
        return f'Las dimensiones de las matrices son inconptibles para la multiplicación'
    return a @ b

def concatenar(a, b):
    if a.shape[1] != b.shape[1]:
        return f'Las matrices deben tener el mismo número de columnas para concatenar'
    return np.concatenate((a, b), axis=0)

def transponer(a):
    return a.T

In [10]:
# Example arrays
a = np.array([[0, 1, 2], 
            [3, 4, 5], 
            [6, 7, 8]])

b = np.array([[0, 1, 2], 
            [3, 4, 5], 
            [6, 7, 8]])

# Addition example
result = array_calculator(a, b, '+')
print(result)
# Expected output:
# array([[ 0,  2,  4],
#        [ 6,  8, 10],
#        [12, 14, 16]])

# Invalid operation example
result = array_calculator(a, b, '&')
print(result)
# Should raise ValueError with message: "Operation '&' not supported"

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
Operación no válida
