Nombre y apellidos: ALFONSO ÍÑIGUEZ CORTÉS
\
Gmail: aic35@alu.ua.es
\
Grupo: 3

# EJERCICIO 1

El ejercicio 1 nos pide redactar un informe de todo lo aprendido en la práctica 1. Para ello voy a seguir la estructura usada en dicha práctica con fin de explicar los conceptos de forma ordenada y coherente

## 0. Numpy

Para esta práctica, vamos a aprender a usar la librería Numpy. A lo largo de las prácticas de la asignatura de matematicas discretas, vamos a ir aprendiendo las principales bilbiotecas de python. Para este práctica, vamos a abordar Numpy. Esta librería nos permite principalmente trabajar con matrices y arrays numéricos. El objetivo de esta práctica pues es conocer las distintas operaciones que nos permite numpy con dichos arrays y matrices (principalmente).

In [ ]:
import numpy as np

## 1. Creación de matrices

En esta sección vamos a definir como se crean los arrays usando la librería Numpy. Los arrays son estructuras de datos que almacenan una pila de elementos del mismo tipo. Para obtener estos arrays, usamos la función que nos proporciona numpy: array. Esta función recibe una lista y devuelve su array.

In [ ]:
array = np.array([0,5,10,20,25,30])    # Creamos el array
print(array)    # Mostramos el array por pantalla 

[ 0  5 10 20 25 30]


Para formar una matriz, solo tenemos que crear el array (con el mismo método explicado arriba) usando una lista que contiene listas. Vamos a formular un ejemplo para ver su funcionamiento

In [ ]:
array = np.array([[9,5,2],[1,1,1],[3,2,4]])
print(array)

[[9 5 2]
 [1 1 1]
 [3 2 4]]


Otra función que nos permite esta librería es la de crear arrays con números aleatorios. Para este función usamos random.rand(). Esta función recibe 2 parámetros que van a definir el tamaño del array que nos devuelve. Es decir si ponemos random.rand(2,2) nos va a devolver un array de 2 filas y 2 columnas (2x2). Los números aleatorios guardados en los arrays se escogen en un rango de 0 a 1.Vamos a poner un ejemplo de ello:

In [ ]:
array_aleatorio = np.random.rand(2,2)
array_aleatorio2 = np.random.rand(3,2)
print('Array 2x2')
print(array_aleatorio)
print('Array 3x2')
print(array_aleatorio2)

Array 2x2
[[0.46438569 0.87452018]
 [0.68869001 0.29356203]]
Array 3x2
[[0.1188292  0.20719964]
 [0.15687192 0.46778653]
 [0.13591532 0.99329226]]


Para poder obtener el valor de las dimensiones de una matriz, podemos usar `shape`. Vamos a definir una matriz y luego vamos a obtener las dimensiones de esta:

In [4]:
matriz = np.array([[1,1,1],[2,2,2]])
print(matriz.shape)

(2, 3)


In [5]:
import numpy as np

np.random.seed(42) # Fijar semilla para reproducibilidad

# Crear un array de 4 dimensiones
a = np.random.rand(1, 3, 32, 32)
print(a.shape)
# Pasamos a ver como queda la imagen usando matplotlib
import matplotlib.pyplot as plt
plt.imshow(a[0, 0, :, :], cmap='viridis')
plt.colorbar()
plt.savefig('./images/practices/imagen_ejemplo.png') # Guardar gráfico
plt.show()

(1, 3, 32, 32)


ModuleNotFoundError: No module named 'matplotlib'

## Acceso a elementos

El acceso a matrices tiene el mismo sintaxis que para el acceso a los elementos de una lista. Vamos a crear una matriz y luego vamos a acceder a varios elementos de esta:

In [9]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])

elemento = matriz[2,1] # Esto nos va a devolver el elemento 
                        # de la fila 3 y la columna 2
print(matriz)
print('Valor de la fila 3 y columna 2:')
print(elemento)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Valor de la fila 3 y columna 2:
8


Vamos a proponer diversos ejemplos de acceso a matrices con diferentes formas de acceso. Una de estas formas es usar índices negativos:

In [11]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])

elemento = matriz[-1,0] # Esto nos va a devolver el elemento de la fila -1 (la última) 
                         # y la primera columna. 
print(matriz)
print('Valor de la útltima fila y primera columna:')
print(elemento)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Valor de la útltima fila y primera columna:
7


## Slicing

Vamos a ampliar el apartado anterior de acceso a elementos. En este apartado vamos a poder pasar de acceder a un elemento a acceder a filas y columnas completas, submatrices... 
Para el slicing es imprenscindible el uso de ':'. Por ejemplo, si ponemos:
```python
Matriz[:,2] # Se imprimen todos los elementos de la columna 3
```
Se indica de la siguiente forma: [filas, columnas]. Al poner [:,2] indicamos que se recorran los elementos de la primera, segunda y tercera fila que esten en la columna 3

Vamos a proponer varios ejemplos:

In [ ]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
fila = matriz[1, :]  # En este caso se imprime la segunda fila entera
print(matriz)
print('Segunda fila:')
print(fila)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Segunda fila:
[4 5 6]


Ocurre de igual forma para recorrer columnas. Si ponemos por ejemplo [:,2], indicamos que se guarden de la primera, segunda y tercera la fila los elementos de la tercera columna. Esto nos da como resultado la tercera columna:

In [ ]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
fila = matriz[:,2]  # En este caso se imprime la 3 columna
print(matriz)
print('Tercera columna:')
print(fila)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Tercera columna:
[3 6 9]


Haciendo uso de los conceptos anteriores, podemos crear submatrices. 
```python
# Para crear submatrices, tenemos que combinar varias filas con columnas
Matriz[1:,:2]
# Ocurre como con los casos anteriores, donde el esquema es [filas, columnas]

Veamos que se ha indicado en este caso:   [1: , :1] 

- Filas -> 1:    | Se recorren los elementos de la segunda y tercera fila 
- Columnas -> :2 | Se recorren los elementos de la primera y segunda columna

Esto nos deja con una submatriz 2x2 que contiene los elementos dichos, vamos a verlo con un ejemplo:

In [6]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
fila = matriz[1:, :2]  # En este caso se imprime la segunda fila entera
print(matriz)
print('Submatriz:')
print(fila)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Submatriz:
[[4 5]
 [7 8]]


### AÑADIR MAS EJEMPLOS

Numpy también nos ofrece elementos de ordenación de matrices, en concreto usamos el método `sort()`. Por defecto, sort ordena los elementos de forma ascendente, pero si le pasamos el parámetro en 'negativo', lo hace de forma descendente: `-Matriz`. Vamos a poner varios ejemplos de ordenanza tanto de forma ascendente como descendente:

In [7]:
matriz = np.random.randint(0,15, size=(3,3))
print('Matriz sin ordenar:')
print(matriz)
print(f'Matriz ordenada: ')
matriz_ordenada = np.sort(matriz)
print(matriz_ordenada)


Matriz sin ordenar:
[[ 6  2 13]
 [ 6  2  3]
 [ 1  3  4]]
Matriz ordenada: 
[[ 2  6 13]
 [ 2  3  6]
 [ 1  3  4]]


De forma descendente:

###  `terminar...`

## 5.4. Operaciones

Vamos a ver como realizar operaciones entre arrays. Estas operaciones pueden ser en la propia matriz o también con matrices diferentes

### 5.4.1. Operaciones en el mismo array

Vamos a comenzar estudiando las operaciones que podemos hacer sobre el propio array definido. Para ello vamos a crear un array y vamos a operar sobre el:

In [27]:
m = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
print(f'Matriz: \n{m}\n')
print('Matriz + 2:')
print(m + 2)

Matriz: 
[[0 0 0]
 [1 1 1]
 [2 2 2]]

Matriz + 2:
[[2 2 2]
 [3 3 3]
 [4 4 4]]


Vemos como se realiza la operación '+' sobre cada elemento de la matriz. Podemos usar distintos operadores (`-`, `*`, `^`...) para realizar diferentes operaciones. Vamos a ver varios ejemplos:

In [28]:
m = np.array([[10, 10, 10], [0, 0, 0], [5, 5, 5]])
print(f'Matriz: \n{m}\n')
print('Matriz -5:')
print(m -5)

Matriz: 
[[10 10 10]
 [ 0  0  0]
 [ 5  5  5]]

Matriz -5:
[[ 5  5  5]
 [-5 -5 -5]
 [ 0  0  0]]


In [32]:
# Ejemplo para la multiplicación

m = np.array([[5, 5, 5], [0, 1, 2], [2, 1, 0]])
print(f'Matriz: \n{m}\n')
print('Matriz * 2:')
print(m * 2)

# Ejemplo para la multiplicación
print('\nMatriz ** 2:')
print(m ** 2)



Matriz: 
[[5 5 5]
 [0 1 2]
 [2 1 0]]

Matriz * 2:
[[10 10 10]
 [ 0  2  4]
 [ 4  2  0]]

Matriz ** 2:
[[25 25 25]
 [ 0  1  4]
 [ 4  1  0]]


Hemos obvservado nuevamente como las operaciones se realizan en todos los elementos de la matriz. Ahora, vamos a ver funciones que podemos usar para calcular distintas operaciones con filas/columnas enteras de la matriz. Vamos a comenzar viendo la función `sum()`. Esta función permite calcular la suma entre los valores que se especifiquen. Vamos a ver algunos ejemplos: 


In [37]:
m = np.array([[0, 0, 0], [10, 10, 10], [10, 10, 10]])
print(m)
print('Suma de todos sus elementos: ')
print(m.sum())

[[ 0  0  0]
 [10 10 10]
 [10 10 10]]
Suma de todos sus elementos: 
60


Otra función que podemos usar para operar sobre nuestra matriz, es la función `mena()`. Esta calcula la media de los valores de una matriz que se especifiquen. Vamos a ver un ejemplo:

In [39]:
m = np.array([[10, 10, 10], [10, 10, 10], [10, 10, 10]])
print(m)
print('Media de todos sus elementos: ')
print(m.mean())

[[10 10 10]
 [10 10 10]
 [10 10 10]]
Media de todos sus elementos: 
10.0


Vemos como estas funciones han ido sumando entre sí todos los elementos de la matriz. Esto ha sido así ya que no le hemos especificado ningún parametro a ninguna de las funciones. Esto es necesario si queremos que se obtenga la suma de ciertas filas o columnas. Para ello tenemos que darle un valor al parámetro `axis`. Vamos a ver ejemplos:

In [49]:
#Vamos a obtener la suma total de las columnas de nuestro array

m = np.array([[10, 20, 30], [10, 20, 30], [10, 20, 30]])
print(m)
print('Suma de las columnas: ')
print(m.sum(axis=0))

[[10 20 30]
 [10 20 30]
 [10 20 30]]
Suma de las columnas: 
[30 60 90]


De la misma forma podemos obtener las medias de las columnas o filas que le especifiquemos a la función `mean()`:

In [ ]:
#Vamos a obtener la media de las 3 filas

m = np.array([[10, 10, 10], [20, 20, 20], [30, 30, 30]])
print(m)
print('Media de las filas: ')
print(m.mean(axis=1))

[[10 10 10]
 [20 20 20]
 [30 30 30]]
Media de las filas: 
[10. 20. 30.]


### Operaciones en diferentes arrays

Vamos a estudiar ahora como podemos realizar operaciones ya no en una misma matriz, si no en diferentes. Nuevamente podemos usar los operandos `+`, `-`, ... Vamos a poner varios ejemplos:

In [50]:
import numpy as np

# Crear dos arrays de 2 dimensiones

a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
b = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print(a + b)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
