#### ALFONSO ÍÑIGUEZ CORTÉS

# EJERCICIO 1

El ejercicio 1 nos pide redactar un informe de todo lo aprendido en la práctica 1. Para ello voy a seguir la estructura usada en dicha práctica con fin de explicar los conceptos de forma ordenada y coherente

## 0. Numpy

Para esta práctica, vamos a aprender a usar la librería Numpy. A lo largo de las prácticas de la asignatura de matematicas discretas, vamos a ir aprendiendo las principales bilbiotecas de python. Para este práctica, vamos a abordar Numpy. Esta librería nos permite principalmente trabajar con matrices y arrays numéricos. El objetivo de esta práctica pues es conocer las distintas operaciones que nos permite numpy con dichos arrays y matrices (principalmente).

In [5]:
import numpy as np

## 1. Creación de matrices

En esta sección vamos a definir como se crean los arrays usando la librería Numpy. Los arrays son estructuras de datos que almacenan una pila de elementos del mismo tipo. Para obtener estos arrays, usamos la función que nos proporciona numpy: array. Esta función recibe una lista y devuelve su array.

In [6]:
array = np.array([0,5,10,20,25,30])    # Creamos el array
print(array)    # Mostramos el array por pantalla 

[ 0  5 10 20 25 30]


Para formar una matriz, solo tenemos que crear el array (con el mismo método explicado arriba) usando una lista que contiene listas. Vamos a formular un ejemplo para ver su funcionamiento

In [20]:
array = np.array([[9,5,2],[1,1,1],[3,2,4]])
print(array)

[[9 5 2]
 [1 1 1]
 [3 2 4]]


Otra función que nos permite esta librería es la de crear arrays con números aleatorios. Para este función usamos random.rand(). Esta función recibe 2 parámetros que van a definir el tamaño del array que nos devuelve. Es decir si ponemos random.rand(2,2) nos va a devolver un array de 2 filas y 2 columnas (2x2). Los números aleatorios guardados en los arrays se escogen en un rango de 0 a 1.Vamos a poner un ejemplo de ello:

In [25]:
array_aleatorio = np.random.rand(2,2)
array_aleatorio2 = np.random.rand(3,2)
print('Array 2x2')
print(array_aleatorio)
print('Array 3x2')
print(array_aleatorio2)

Array 2x2
[[0.46438569 0.87452018]
 [0.68869001 0.29356203]]
Array 3x2
[[0.1188292  0.20719964]
 [0.15687192 0.46778653]
 [0.13591532 0.99329226]]
