Nombre y apellidos: ALFONSO ÍÑIGUEZ CORTÉS
\
Gmail: aic35@alu.ua.es
\
Grupo: 3

In [15]:
array1 = array()
array2 = 
operation = '+'
print(array_calculado,,array1,array2)

SyntaxError: invalid syntax (1354393398.py, line 2)

# EJERCICIO 1

El ejercicio 1 nos pide redactar un informe de todo lo aprendido en la práctica 1. Para ello voy a seguir la estructura usada en dicha práctica con fin de explicar los conceptos de forma ordenada y coherente

## 0. Numpy

Para esta práctica, vamos a aprender a usar la librería Numpy. A lo largo de las prácticas de la asignatura de matematicas discretas, vamos a ir aprendiendo las principales bilbiotecas de python. Para este práctica, vamos a abordar Numpy. Esta librería nos permite principalmente trabajar con matrices y arrays numéricos. El objetivo de esta práctica pues es conocer las distintas operaciones que nos permite numpy con dichos arrays y matrices (principalmente).

In [3]:
import numpy as np

## 1. Creación de matrices

En esta sección vamos a definir como se crean los arrays usando la librería Numpy. Los arrays son estructuras de datos que almacenan una pila de elementos del mismo tipo. Para obtener estos arrays, usamos la función que nos proporciona numpy: array. Esta función recibe una lista y devuelve su array.

In [6]:
array = np.array([0,5,10,20,25,30])    # Creamos el array
print(array)    # Mostramos el array por pantalla 

[ 0  5 10 20 25 30]


Para formar una matriz, solo tenemos que crear el array (con el mismo método explicado arriba) usando una lista que contiene listas. Vamos a formular un ejemplo para ver su funcionamiento

In [20]:
array = np.array([[9,5,2],[1,1,1],[3,2,4]])
print(array)

[[9 5 2]
 [1 1 1]
 [3 2 4]]


Otra función que nos permite esta librería es la de crear arrays con números aleatorios. Para este función usamos random.rand(). Esta función recibe 2 parámetros que van a definir el tamaño del array que nos devuelve. Es decir si ponemos random.rand(2,2) nos va a devolver un array de 2 filas y 2 columnas (2x2). Los números aleatorios guardados en los arrays se escogen en un rango de 0 a 1.Vamos a poner un ejemplo de ello:

In [25]:
array_aleatorio = np.random.rand(2,2)
array_aleatorio2 = np.random.rand(3,2)
print('Array 2x2')
print(array_aleatorio)
print('Array 3x2')
print(array_aleatorio2)

Array 2x2
[[0.46438569 0.87452018]
 [0.68869001 0.29356203]]
Array 3x2
[[0.1188292  0.20719964]
 [0.15687192 0.46778653]
 [0.13591532 0.99329226]]


In [4]:
array = np.random.rand(5,5)
print(array.shape)

(5, 5)


## Acceso a elementos

El acceso a matrices tiene el mismo sintaxis que para el acceso a los elementos de una lista. Vamos a crear una matriz y luego vamos a acceder a varios elementos de esta:

In [7]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])

elemento = matriz[0,0] # Esto nos va a devolver el elemento de la fila 0 y la columna 0
                  # En este caso guardamos el valor del primer elemento de la matriz: 1
print(elemento)

1


Vamos a proponer diversos ejemplos de acceso a matrices con diferentes formas de acceso. Una de estas formas es usar índices negativos:

In [9]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])

elemento = matriz[-1,-1] # Esto nos va a devolver el elemento de la fila -1 (la última) 
                         # y la columna -2. En este caso guardamos el valor del último 
                         # elemento de la matriz: 9
print(elemento)

9


## Slicing

Vamos a ampliar el apartado anterior de acceso a elementos. En este apartado vamos a poder pasar de acceder a un elemento a acceder a filas y columnas completas, submatrices... 
Para el slicing es imprenscindible el uso de ':'. Por ejemplo, si ponemos:
```python
Matriz[:,2] # Se imprimen todos los elementos de la columna 3
```
Se indica de la siguiente forma: [filas, columnas]. Al poner [:,2] indicamos que se recorran los elementos de la primera, segunda y tercera fila que esten en la columna 3

Vamos a proponer varios ejemplos:

In [14]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
fila = matriz[1, :]  # En este caso se imprime la segunda fila entera
print(matriz)
print('Segunda fila:')
print(fila)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Segunda fila:
[4 5 6]


Ocurre de igual forma para recorrer columnas. Si ponemos por ejemplo [:,2], indicamos que se guarden de la primera, segunda y tercera la fila los elementos de la tercera columna. Esto nos da como resultado la tercera columna:

In [18]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
fila = matriz[:,2]  # En este caso se imprime la 3 columna
print(matriz)
print('Tercera columna:')
print(fila)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Tercera columna:
[3 6 9]


Haciendo uso de los conceptos anteriores, podemos crear submatrices. 
```python
# Para crear submatrices, tenemos que combinar varias filas con columnas
Matriz[1:,:2]
# Ocurre como con los casos anteriores, donde el esquema es [filas, columnas]

Veamos que se ha indicado en este caso:   [1: , :1] \
Filas -> 1:    | Se recorren los elementos de la segunda y tercera fila \
Columnas -> :2 | Se recorren los elementos de la primera y segunda columna

Esto nos deja con una submatriz 2x2 que contiene los elementos dichos, vamos a verlo con un ejemplo:

In [26]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
fila = matriz[1:, :2]  # En este caso se imprime la segunda fila entera
print(matriz)
print('Submatriz:')
print(fila)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Submatriz:
[[4 5]
 [7 8]]


In [ ]:
h