Nombre y apellidos: ALFONSO ÍÑIGUEZ CORTÉS
\
Gmail: aic35@alu.ua.es
\
Grupo: 3

# EJERCICIO 1

El ejercicio 1 nos pide redactar un informe de todo lo aprendido en la práctica 1. Para ello voy a seguir la estructura usada en dicha práctica con fin de explicar los conceptos de forma ordenada y coherente

## 0. Numpy

Para esta práctica, vamos a aprender a usar la librería Numpy. A lo largo de las prácticas de la asignatura de matematicas discretas, vamos a ir aprendiendo las principales bilbiotecas de python. Para este práctica, vamos a abordar Numpy. Esta librería nos permite principalmente trabajar con matrices y arrays numéricos. El objetivo de esta práctica pues es conocer las distintas operaciones que nos permite numpy con dichos arrays y matrices (principalmente).

In [ ]:
import numpy as np

## 1. Creación de matrices

En esta sección vamos a definir como se crean los arrays usando la librería Numpy. Los arrays son estructuras de datos que almacenan una pila de elementos del mismo tipo. Para obtener estos arrays, usamos la función que nos proporciona numpy: array. Esta función recibe una lista y devuelve su array.

In [ ]:
array = np.array([0,5,10,20,25,30])    # Creamos el array
print(array)    # Mostramos el array por pantalla 

[ 0  5 10 20 25 30]


Para formar una matriz, solo tenemos que crear el array (con el mismo método explicado arriba) usando una lista que contiene listas. Vamos a formular un ejemplo para ver su funcionamiento

In [ ]:
array = np.array([[9,5,2],[1,1,1],[3,2,4]])
print(array)

[[9 5 2]
 [1 1 1]
 [3 2 4]]


Otra función que nos permite esta librería es la de crear arrays con números aleatorios. Para este función usamos random.rand(). Esta función recibe 2 parámetros que van a definir el tamaño del array que nos devuelve. Es decir si ponemos random.rand(2,2) nos va a devolver un array de 2 filas y 2 columnas (2x2). Los números aleatorios guardados en los arrays se escogen en un rango de 0 a 1.Vamos a poner un ejemplo de ello:

In [ ]:
array_aleatorio = np.random.rand(2,2)
array_aleatorio2 = np.random.rand(3,2)
print('Array 2x2')
print(array_aleatorio)
print('Array 3x2')
print(array_aleatorio2)

Array 2x2
[[0.46438569 0.87452018]
 [0.68869001 0.29356203]]
Array 3x2
[[0.1188292  0.20719964]
 [0.15687192 0.46778653]
 [0.13591532 0.99329226]]


Para poder obtener el valor de las dimensiones de una matriz, podemos usar `shape`. Vamos a definir una matriz y luego vamos a obtener las dimensiones de esta:

In [4]:
matriz = np.array([[1,1,1],[2,2,2]])
print(matriz.shape)

(2, 3)


In [5]:
import numpy as np

np.random.seed(42) # Fijar semilla para reproducibilidad

# Crear un array de 4 dimensiones
a = np.random.rand(1, 3, 32, 32)
print(a.shape)
# Pasamos a ver como queda la imagen usando matplotlib
import matplotlib.pyplot as plt
plt.imshow(a[0, 0, :, :], cmap='viridis')
plt.colorbar()
plt.savefig('./images/practices/imagen_ejemplo.png') # Guardar gráfico
plt.show()

(1, 3, 32, 32)


ModuleNotFoundError: No module named 'matplotlib'

## Acceso a elementos

El acceso a matrices tiene el mismo sintaxis que para el acceso a los elementos de una lista. Vamos a crear una matriz y luego vamos a acceder a varios elementos de esta:

In [9]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])

elemento = matriz[2,1] # Esto nos va a devolver el elemento 
                        # de la fila 3 y la columna 2
print(matriz)
print('Valor de la fila 3 y columna 2:')
print(elemento)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Valor de la fila 3 y columna 2:
8


Vamos a proponer diversos ejemplos de acceso a matrices con diferentes formas de acceso. Una de estas formas es usar índices negativos:

In [11]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])

elemento = matriz[-1,0] # Esto nos va a devolver el elemento de la fila -1 (la última) 
                         # y la primera columna. 
print(matriz)
print('Valor de la útltima fila y primera columna:')
print(elemento)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Valor de la útltima fila y primera columna:
7


## Slicing

Vamos a ampliar el apartado anterior de acceso a elementos. En este apartado vamos a poder pasar de acceder a un elemento a acceder a filas y columnas completas, submatrices... 
Para el slicing es imprenscindible el uso de ':'. Por ejemplo, si ponemos:
```python
Matriz[:,2] # Se imprimen todos los elementos de la columna 3
```
Se indica de la siguiente forma: [filas, columnas]. Al poner [:,2] indicamos que se recorran los elementos de la primera, segunda y tercera fila que esten en la columna 3

Vamos a proponer varios ejemplos:

In [ ]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
fila = matriz[1, :]  # En este caso se imprime la segunda fila entera
print(matriz)
print('Segunda fila:')
print(fila)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Segunda fila:
[4 5 6]


Ocurre de igual forma para recorrer columnas. Si ponemos por ejemplo [:,2], indicamos que se guarden de la primera, segunda y tercera la fila los elementos de la tercera columna. Esto nos da como resultado la tercera columna:

In [ ]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
fila = matriz[:,2]  # En este caso se imprime la 3 columna
print(matriz)
print('Tercera columna:')
print(fila)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Tercera columna:
[3 6 9]


Haciendo uso de los conceptos anteriores, podemos crear submatrices. 
```python
# Para crear submatrices, tenemos que combinar varias filas con columnas
Matriz[1:,:2]
# Ocurre como con los casos anteriores, donde el esquema es [filas, columnas]

Veamos que se ha indicado en este caso:   [1: , :1] 

- Filas -> 1:    | Se recorren los elementos de la segunda y tercera fila 
- Columnas -> :2 | Se recorren los elementos de la primera y segunda columna

Esto nos deja con una submatriz 2x2 que contiene los elementos dichos, vamos a verlo con un ejemplo:

In [6]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
fila = matriz[1:, :2]  # En este caso se imprime la segunda fila entera
print(matriz)
print('Submatriz:')
print(fila)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Submatriz:
[[4 5]
 [7 8]]


### AÑADIR MAS EJEMPLOS

Numpy también nos ofrece elementos de ordenación de matrices, en concreto usamos el método `sort()`. Por defecto, sort ordena los elementos de forma ascendente, pero si le pasamos el parámetro en 'negativo', lo hace de forma descendente: `-Matriz`. Vamos a poner varios ejemplos de ordenanza tanto de forma ascendente como descendente:

In [7]:
matriz = np.random.randint(0,15, size=(3,3))
print('Matriz sin ordenar:')
print(matriz)
print(f'Matriz ordenada: ')
matriz_ordenada = np.sort(matriz)
print(matriz_ordenada)


Matriz sin ordenar:
[[ 6  2 13]
 [ 6  2  3]
 [ 1  3  4]]
Matriz ordenada: 
[[ 2  6 13]
 [ 2  3  6]
 [ 1  3  4]]


De forma descendente:

###  `terminar...`

## 5.4. Operaciones

Vamos a ver como realizar operaciones entre arrays. Estas operaciones pueden ser en la propia matriz o también con matrices diferentes

### 5.4.1. Operaciones en el mismo array

Vamos a comenzar estudiando las operaciones que podemos hacer sobre el propio array definido. Para ello vamos a crear un array y vamos a operar sobre el:

In [27]:
m = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
print(f'Matriz: \n{m}\n')
print('Matriz + 2:')
print(m + 2)

Matriz: 
[[0 0 0]
 [1 1 1]
 [2 2 2]]

Matriz + 2:
[[2 2 2]
 [3 3 3]
 [4 4 4]]


Vemos como se realiza la operación '+' sobre cada elemento de la matriz. Podemos usar distintos operadores (`-`, `*`, `^`...) para realizar diferentes operaciones. Vamos a ver varios ejemplos:

In [28]:
m = np.array([[10, 10, 10], [0, 0, 0], [5, 5, 5]])
print(f'Matriz: \n{m}\n')
print('Matriz -5:')
print(m -5)

Matriz: 
[[10 10 10]
 [ 0  0  0]
 [ 5  5  5]]

Matriz -5:
[[ 5  5  5]
 [-5 -5 -5]
 [ 0  0  0]]


In [32]:
# Ejemplo para la multiplicación

m = np.array([[5, 5, 5], [0, 1, 2], [2, 1, 0]])
print(f'Matriz: \n{m}\n')
print('Matriz * 2:')
print(m * 2)

# Ejemplo para la multiplicación
print('\nMatriz ** 2:')
print(m ** 2)



Matriz: 
[[5 5 5]
 [0 1 2]
 [2 1 0]]

Matriz * 2:
[[10 10 10]
 [ 0  2  4]
 [ 4  2  0]]

Matriz ** 2:
[[25 25 25]
 [ 0  1  4]
 [ 4  1  0]]


Hemos obvservado nuevamente como las operaciones se realizan en todos los elementos de la matriz. Ahora, vamos a ver funciones que podemos usar para calcular distintas operaciones con filas/columnas enteras de la matriz. Vamos a comenzar viendo la función `sum()`. Esta función permite calcular la suma entre los valores que se especifiquen. Vamos a ver algunos ejemplos: 


In [37]:
m = np.array([[0, 0, 0], [10, 10, 10], [10, 10, 10]])
print(m)
print('Suma de todos sus elementos: ')
print(m.sum())

[[ 0  0  0]
 [10 10 10]
 [10 10 10]]
Suma de todos sus elementos: 
60


Otra función que podemos usar para operar sobre nuestra matriz, es la función `mena()`. Esta calcula la media de los valores de una matriz que se especifiquen. Vamos a ver un ejemplo:

In [39]:
m = np.array([[10, 10, 10], [10, 10, 10], [10, 10, 10]])
print(m)
print('Media de todos sus elementos: ')
print(m.mean())

[[10 10 10]
 [10 10 10]
 [10 10 10]]
Media de todos sus elementos: 
10.0


Vemos como estas funciones han ido sumando entre sí todos los elementos de la matriz. Esto ha sido así ya que no le hemos especificado ningún parametro a ninguna de las funciones. Esto es necesario si queremos que se obtenga la suma de ciertas filas o columnas. Para ello tenemos que darle un valor al parámetro `axis`. Vamos a ver ejemplos:

In [49]:
#Vamos a obtener la suma total de las columnas de nuestro array

m = np.array([[10, 20, 30], [10, 20, 30], [10, 20, 30]])
print(m)
print('Suma de las columnas: ')
print(m.sum(axis=0))

[[10 20 30]
 [10 20 30]
 [10 20 30]]
Suma de las columnas: 
[30 60 90]


De la misma forma podemos obtener las medias de las columnas o filas que le especifiquemos a la función `mean()`:

In [ ]:
#Vamos a obtener la media de las 3 filas

m = np.array([[10, 10, 10], [20, 20, 20], [30, 30, 30]])
print(m)
print('Media de las filas: ')
print(m.mean(axis=1))

[[10 10 10]
 [20 20 20]
 [30 30 30]]
Media de las filas: 
[10. 20. 30.]


### Operaciones en diferentes arrays

Vamos a estudiar ahora como podemos realizar operaciones ya no en una misma matriz, si no en diferentes. Nuevamente podemos usar los operandos `+`, `-`, ... Vamos a poner varios ejemplos:

In [ ]:
m = np.array([[0, 0, 0], [3, 4, 5], [6, 7, 8]])
m1 = np.array([[0, 0, 0], [9, 9, 9], [6, 7, 8]])

print(m + m1)

[[ 0  0  0]
 [12 13 14]
 [12 14 16]]


Es muy importante mencionar que para poder realizar restas o sumas sobre dos arrays diferentes, estos tienen que tener las mismas dimensiones. Para reazliar una multiplicación entre dos matrices, el número de columnas de la primera matriz ha de coincidir con el número de filas de la segunda. Ambas condiciones deben de cumplirse siempre que se quieran realizar dichas operaciones. Vamos a verlo:

In [11]:
m2 = np.array([[1,5,10],[5,10,15],[10,15,20]])
m1 = np.array([[1,5,10],[5,10,15],[10,15,20]])

if m1.shape == m2.shape:
    print(f'm1:\n{m1}\nm2:\n{m2}\n')
    print(f'Dimensiones de la matriz 1: {m1.shape}\nDimensiones de la matriz 1: {m2.shape}\n')
    print(f'Suma:\n{m1+m2}')
else:
    print('Dimensiones no compatibles')

m1:
[[ 1  5 10]
 [ 5 10 15]
 [10 15 20]]
m2:
[[ 1  5 10]
 [ 5 10 15]
 [10 15 20]]

Dimensiones de la matriz 1: (3, 3)
Dimensiones de la matriz 1: (3, 3)

Suma:
[[ 2 10 20]
 [10 20 30]
 [20 30 40]]


Para relizar la multiplicación de matrices usamos `@`. Este operador no multipilca elemento a elemento como lo hace `*`, si no que realiza la multiplicación matricial (filas * columnas...)

In [ ]:
m2 = np.array([[1,1,1],[5,10,15],[10,15,20]])
m1 = np.array([[2,2,2],[2,2,2],[2,2,2]])

print(f'm1:\n{m1}\nm2:\n{m2}\n')
print('Si usamos "*":')
print(f'{m1*m2}\nPodemos comprobar como se ha multplicadon entre sí los elementos de la misma posición\n')
print('Si usamos "*":')
print(f'{m1@m2}\nSe ha realizado la multiplicacion matricial')

m1:
[[2 2 2]
 [2 2 2]
 [2 2 2]]
m2:
[[ 1  1  1]
 [ 5 10 15]
 [10 15 20]]

Si usamos "*":
[[ 2  2  2]
 [10 20 30]
 [20 30 40]]
Podemos comprobar como se ha multplicadon entre sí los elementos de la misma posición

Si usamos "*":
[[32 52 72]
 [32 52 72]
 [32 52 72]]
Se ha realizado la multiplicacion matricial


## Broadcasting

Normalmente se suelen dar casos donde tenemos un array mas pequeño (como por ejemplo, un vector) y otros mas grandes (matrices). El boradcasting es un método óptimo para trabajar con matrices de diferentes formas en respecto a operaciones aritméticas. Hay casos donde queremos usar este array pequeño para realizar alguna operación sobre el array mayor. Por ejemplo:

In [29]:
m = np.array([[0,0,0],[5,5,5],[10,10,10]])
vector = np.array([5,5,5])

print(m + vector) #Hemos sumado 5 (5,5,5) a cada fila

[[ 5  5  5]
 [10 10 10]
 [15 15 15]]


El problema aparece cuando el tamaño del array que tenemos es mucho más grande. Es ineficiente crear una matriz grande donde cada fila sea el vector para sumarselas a la matriz. El broadcasting de Numpy nos permite realizar ese cálculo sin la necesidad de crear múltiples copias de b,a,b,a...

Para relizar `broadcasting` sobre dos arrays juntos, se deben cumplir:
- Si los arrays no tienen el mismo rango, se adelantan 1s a la forma del arreglo de rango inferior hasta que ambas formas tengan la misma longitud.

- Se dice que los dos arrays son compatibles en una dimensión si tienen el mismo tamaño en la dimensión, o si uno de los arrays tiene tamaño 1 en esa dimensión.

- Los arrays pueden emitirse entre sí si son compatibles en todas las dimensiones.

- Tras la difusión, cada array se comporta como si tuviera forma igual al máximo elemental de formas de los dos arrays de entrada.

- En cualquier dimensión donde un array tenía tamaño 1 y el otro array mayor que 1, el primer array se comporta como si hubiera sido copiado a lo largo de esa dimensión.

Otra forma con respecto a la remodelación del vector para que se un vector de forma,  es usando la función `reshape()`. Esta función recive como parámetros las dimensiones a las que se quiere remodelar. Véase un ejemplo:

In [35]:
m1 = np.array([[0, 1, 21], [3, 42, 5], [6, 75, 8]])
m2 = np.array([5, 5, 5])

print(m1 + m2.reshape((3,1)))

[[ 5  6 26]
 [ 8 47 10]
 [11 80 13]]


## Operadores de comparación

La librería de numpy tambien nos permite realizar operaciones de comparación entre diferentes arrays. Vamos a ver un ejemplo donde comparemos que elementos de la matriz son mayores que 1:

In [40]:
s = np.random.seed(40)
m1 = np.random.randint(0,2,(3,3))
print(m1)

print(f'\nValores mayores que 0:\n{m1 > 0}')

[[0 1 1]
 [1 0 0]
 [0 1 0]]

Valores mayores que 0:
[[False  True  True]
 [ True False False]
 [False  True False]]


Vemos como en los valores que cumplen la condición establecida ('>0'), se coloca ``True``, mientras que si no se cumple la condición se coloca en la posición ``False``. Esto es sumamente útil cuando queremos filtrar elementos de una matriz. 

In [ ]:
m1 = np.array([[5, 5, 5], [0, 0, 0], [10, 10, 10]])
m2 = np.array([5, 0, 10])

print(m1[m2 == 5])

[[5 5 5]]


Vemos como se han imprimido los valores de la primera fila de m1. ¿Por qué? -> La clave esta en la siguiente línea de código:
```python
print(m1[m2 == 5])
```
En esta linea especificamos que se impriman los valores que esten en la posición de m2 que sean iguales a 5. Si nos fijamos en m2, que es un array de 1 dimension, la condición de =5, se cumple en la posición 0. Luego de nuestra matriz m1 se va a imprimir esta misma posición. Esta forma es una buena práctica para filtrar elementos de una matriz


## Operadores lógicos

Numpy también incluye operadores lógicos entre las operaciones que incluye. Vamos a poner ejemplos de algunos de estos, como `and, or, not...` Para poder usar estos operadores en python, hacemos lo siguiente:
- AND = "&"
- OR = "|"
- NOT = "~"

Vemos un ejemplo con ``&``:

In [76]:
m1 = np.random.randint(0,11,(3,3))
m2 = np.random.randint(0,11,(3,3))

print('AND')
print(m1)
print('----------')
print(m2)
print('----------')         # Para 'and' -> usamos &
print((m1 > 2) & (m2 < 5))  # True si y solo si se cumplen AMBAS condiciones
                            # En este caso, se imprime true en las posiciones donde en 
                            # la primera matriz es >2 Y en la segunda es <5

AND
[[2 1 3]
 [6 5 8]
 [0 9 4]]
----------
[[3 1 9]
 [5 3 3]
 [4 1 2]]
----------
[[False False False]
 [False  True  True]
 [False  True  True]]


Vemos ahora el operador `|`:

In [ ]:
m1 = np.random.randint(0,11,(3,3))
m2 = np.random.randint(0,11,(3,3))

print('OR')
print(m1)
print('----------')
print(m2)
print('----------')         # Para 'or' -> usamos |
print((m1 > 2) | (m2 < 5))  # True si y solo si se cumplen UNA de las condiciones
                            # En este caso, se imprime true en las posiciones donde en 
                            # la primera matriz es >2 O en la segunda es <5. Dicho de otra 
                            # forma, solo se pone False sin no se cumple ninguna de las condiciones

Vemos ahora el operador `~`:

In [85]:
m1 = np.random.randint(0,11,(3,3))

print('NOT')
print(m1)
print('----------') 
print('Posiciones cuyo valor es menor a 5:')   # Para 'not' -> usamos ~
print(~(m1 >= 5))                              # True si solo si NO se cumple la condición
                                               # En este caso, se imprime true en las posiciones 
                                               # donde el valor de la misma es menor a 5
                            

NOT
[[8 2 3]
 [9 4 3]
 [1 8 2]]
----------
Posiciones cuyo valor es menor a 5:
[[False  True  True]
 [False  True  True]
 [ True False  True]]


## Localización de elementos

Otra cosa que podemos hacer es localizar elementos en una array que cumplan cierta condición. Esta utilidad es muy buena para filtrar los elementos de una matriz. Para esto, Numpy nps ofrece la función `where()`. Vamos a explicar que devuelve esta función:

`where()` 
-> La función devuelve una tupla de arrays. Estos arrays contienen los ínidices donde se cumplen la condición establecida. Si le pasamos una matriz 3x3, `where()` nos va a devolver una tupla con dos arrays
- El primer array : Contiene los índices de las filas
- El segundo array: Contiene los ínidices de las columnas

Entonces, si tenemos la matriz:
```python
matriz = np.array([0,0,0],[1,1,1],[2,2,2])
cumplen_condicion = np.where(matriz == 1)
```
Estamos intentando seleccionar los elementos de la matriz que sean iguales a 1. Si nos fijamos en la matriz de ejemplo, vemos como esto solo ocurre en los 3 valores de la segunda fila. Vemos que nos devuelve where():
1. array([1,1,1])  Los 3 elementos estan en la segunda fila 
2. array([0,1,2])  Los 3 elementos estan cada uno en una columna (la 1, 2 y 3)

Vamos a escribir este ejemplo con código para comprobar el funcionamiento

In [21]:
matriz = np.array([[0,0,0],[1,1,1],[2,2,2]])
cumplen_condicion = np.where(matriz == 1)
print(matriz)
print(f'Indices de las filas: {cumplen_condicion[0]}')
print(f'Indices de las columnas: {cumplen_condicion[1]}')
print(cumplen_condicion)


[[0 0 0]
 [1 1 1]
 [2 2 2]]
Indices de las filas: [1 1 1]
Indices de las columnas: [0 1 2]
(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))


Numpy nos ofrece mas funciones para filtrar elementos de una matriz. Vamos a estuidar ahora la función ´nonzero()´. Esta función devuelve los elementos que sean distintos a 0 ( != 0 ). También devuelve una tupla con arrays. Estos contienen los índieces de filas y columnas de los valores distintos a cero. Esto ya ha sido explicado al principio de este apartado. Vamos a ver un ejemplo:

In [20]:
matriz = np.array([[0,0,0],[1,1,1],[2,2,2]])
print(matriz)
print(f'Indices de las filas: {cumplen_condicion[0]}')
print(f'Indices de las columnas: {cumplen_condicion[1]}')
print(matriz.nonzero())

[[0 0 0]
 [1 1 1]
 [2 2 2]]
Indices de las filas: [1 1 1]
Indices de las columnas: [0 1 2]
(array([1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))


Podemos combinar también ambas funciones para localicar elementos con más condiciones. Vamos a combinar `where()` y `nonzero()` con el siguiente ejemplo:

In [ ]:
matriz = np.array([[5,5,5],[0,0,0],[7,7,7]])
print(f'Índices donde matriz < 6: {np.where(matriz < 6)}')
print(f'Índices donde matriz < 6 y no es 0: {np.nonzero(np.where(matriz < 6))}')

Índices donde matriz < 6: (array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))
Índices donde matriz > 6 y no es 0: (array([0, 0, 0, 1, 1, 1, 1], dtype=int64), array([3, 4, 5, 1, 2, 4, 5], dtype=int64))


# ARREGLAR

## Triu and tril

Otra funcionalidad de Numpy es la de obtener matrices triangulares, tanto de forma superior como inferior. Para el caso de que queramos obtener la triangular superior, usamos `triu`. Vamos a verlo con un ejemplo:

In [23]:
m = np.random.randint(0,11,(3,3))
print(f'Matriz orginal:\n{m}')
print(f'\nMatriz triangular superior:\n{np.triu(m)}')

Matriz orginal:
[[7 9 1]
 [3 2 1]
 [2 0 7]]

Matriz triangular superior:
[[7 9 1]
 [0 2 1]
 [0 0 7]]


Para obtener la matriz triangular inferior, usamos `tril`. Vamos nuevamente a ver un ejemplo:

In [24]:
m = np.random.randint(0,11,(3,3))
print(f'Matriz orginal:\n{m}')
print(f'\nMatriz triangular superior:\n{np.tril(m)}')

Matriz orginal:
[[ 4  4  7]
 [ 3  8 10]
 [ 7  6  6]]

Matriz triangular superior:
[[4 0 0]
 [3 8 0]
 [7 6 6]]


## Manipulación de la forma de las matrices

Numpy tambien nos permite realizar diversas operaciones sobre una matriz con el objetivo de cambiarle la forma. Una función que ofrece esta libreía por este motivo es `flatten()`. Esta función cambia la forma de una matriz de tal forma que, por ejemplo, una matriz de 3x3 dimensiones passa a ser de 1x6. Digamos que solo deja una fila, las demas filas pasar a ser columnas. Vamos a comprenderlo mejor con un ejemplo:

In [ ]:
m = np.array([['fila1', 'fila1', 'fila1'], ['fila2', 'fila2', 'fila2'], ['fila3', 'fila3', 'fila3']])
print(f'Matriz original:\n {m}\nflatten():')
print(m.flatten())

Matriz original:
 [['fila1' 'fila1' 'fila1']
 ['fila2' 'fila2' 'fila2']
 ['fila3' 'fila3' 'fila3']]
flatten():
['fila1' 'fila1' 'fila1' 'fila2' 'fila2' 'fila2' 'fila3' 'fila3' 'fila3']


También podemos calcular la matriz transupuesta de otra matriz. Esta operación es básica y fundamental a la hora de hacer cálculos con matrices. Para hacerlo solo es necesrio el atrbiuto `T`. Vemos un ejemplo:

In [34]:
matriz = np.array([[5,5,5],[0,0,0],[7,7,7]])
print(f'Matriz original:\n {matriz}\nTranspuesta:')
print(matriz.T)

Matriz original:
 [[5 5 5]
 [0 0 0]
 [7 7 7]]
Transpuesta:
[[5 0 7]
 [5 0 7]
 [5 0 7]]


A la hora de cambiar las dimensiones de un array, Numpy nos ofrece una forma de redimensionar a las dimensiones que nosotros seleccionemos. Esta operación se realiza con la función `reshape()`. Esta función recibe como parémtro las dimensiones a las que queremos actualizar nuestro array. Es importante que las dimensiones objetivo sean compatibles con las originales. Por ejemplo, si tenemos una matriz de 3x3, podríamos redimensionarla ana matriz de 9x1, conviertiendola así es una matriz con una sola columna (con 9 elementos). Lo importante es que el reshape() siempre conserve el número total de elementos de nuestro array. Vamos a verlo con un ejemplo:

In [45]:
matriz = np.array([[5,5,5],[0,0,0],[7,7,7]])
print(f'Matriz original:\n {matriz}\nDimensiones 9x1:')
print(matriz.reshape(9,1))

Matriz original:
 [[5 5 5]
 [0 0 0]
 [7 7 7]]
Dimensiones 9x1:
[[5]
 [5]
 [5]
 [0]
 [0]
 [0]
 [7]
 [7]
 [7]]


## Valores propios

Numpy también nos ofrece opciones para calcular los valores propios y vectores de una matriz. Para hacer esto usamos la función `linalg.eig`, la cual devuelve:
- Array con números (cada uno indica cuánto se escala un vector propio)
- Una matriz donde cada columna es un vector propio
Vamos a ver un ejemplo de ello:

In [53]:
matriz = np.array([[5,5,5],[0,0,0],[7,7,7]])
eigenvalues, eigenvectors = np.linalg.eig(matriz)
print(f'Array de números-> {eigenvalues}')
print(f'Matriz con los vectores propios:\n{eigenvectors}')

Array de números-> [ 0. 12.  0.]
Matriz con los vectores propios:
[[-7.07106781e-001 -5.81238194e-001 -7.07106781e-001]
 [ 0.00000000e+000  0.00000000e+000  1.35389578e-276]
 [ 7.07106781e-001 -8.13733471e-001  7.07106781e-001]]


### COMPROBACIÓN DE DONDE ESTÁN LOS ERROES (LUEGO BORRAR)