Nombre y apellidos: Alfonso Íñiguez Cortés \
gmail: aic35@alu.ua.es \
Grupo: 3

## Ejercicio 3

In [3]:
import numpy as np


# Matriz (con diagonal a 0)
np.random.seed(0)
A = np.random.randint(0, 2, (10, 10))
A[range(10), range(10)] = 0
print("Matriz A:")
print(A)


# Matriz de grado
D = np.zeros((10, 10))
grados = A.sum(axis=1)
D[np.arange(10), np.arange(10)] = grados
print("\nMatriz D:")
print(D)


# Matriz laplaciana
L = np.zeros((10, 10))
L = D - A

print("\nMatriz L:")
print(L)

# Normalizamos la matriz
D_inv = np.linalg.inv(D)
L_norm = D_inv @ L @ D_inv

print("\nMatriz L normalizada:")
print(L_norm)


# Contamos los nodos
def contar_nodos(m_adyacencia, valor):
    grados = np.zeros(10)
    grados = m_adyacencia.sum(axis = 1)
    nodos = np.where(grados >= valor)[0]
    return np.array([len(nodos)])

print("\nNodos con grado mayores o iguales a 6:")
print(contar_nodos(A, 6))

Matriz A:
[[0 1 1 0 1 1 1 1 1 1]
 [1 0 0 1 0 0 0 0 0 1]
 [0 1 0 0 0 1 1 1 1 0]
 [1 0 1 0 1 1 0 1 1 0]
 [0 1 0 1 0 1 1 1 0 1]
 [0 1 1 1 1 0 1 0 0 1]
 [1 0 1 0 1 0 0 0 0 0]
 [1 1 0 0 0 1 1 0 1 0]
 [0 1 0 1 1 1 1 1 0 0]
 [1 1 0 0 1 0 0 1 1 0]]

Matriz D:
[[8. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 6. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 6. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]]

Matriz L:
[[ 8. -1. -1.  0. -1. -1. -1. -1. -1. -1.]
 [-1.  3.  0. -1.  0.  0.  0.  0.  0. -1.]
 [ 0. -1.  5.  0.  0. -1. -1. -1. -1.  0.]
 [-1.  0. -1.  6. -1. -1.  0. -1. -1.  0.]
 [ 0. -1.  0. -1.  6. -1. -1. -1.  0. -1.]
 [ 0. -1. -1. -1. -1.  6. -1.  0.  0. -1.]
 [-1.  0. -1.  0. -1.  0.  3.  0.  0.  0.]
 [-1. -1.  0.  0.  0. -1. -1.  5. -1.  0.]
 [ 0. -1.  0. -1. -1. -1. -1. -1.  6.  0.]
 [-1. -1.  0.  0. -