Nombre y apellidos: Alfonso Íñiguez Cortés \
gmail: aic35@alu.ua.es \
Grupo: 3

## EJERCICIO 2 
### IMPLEMENTACIÓN DE LA CALCULADORA DE MATRIZ NUMPY

In [ ]:
import numpy as np


#main
def array_calculator(array1: np.ndarray, array2: np.ndarray, operacion: str) -> np.ndarray:

    if operacion == '+':
        return sumar(array1, array2)
    elif operacion == '-':
        return restar(array1, array2)
    elif operacion == '*':
        return multiplicar(array1, array2)
    elif operacion == 'concat':
        return concatenar(array1, array2)
    elif operacion == 'transpose':
        return transponer(array1)

    else:
        return f'Operación no válida'
    

#auxiilares
def sumar(a, b):
    if a.shape != b.shape:
        return 'Las matrices deben tener las misms dimensiones para sumarlas'
    return a + b

def restar(a, b):
    if a.shape != b.shape:
        return f'Las matrices deben tener las mismas dimenensiones para que se resten'
    return a - b

def multiplicar(a, b):
    if a.shape[1] != b.shape[0]:
        return f'Las dimensiones de las matrices son inconptibles para la multiplicación'
    return a @ b

def concatenar(a, b):
    if a.shape[1] != b.shape[1]:
        return f'Las matrices deben tener el mismo número de columnas para concatenar'
    return np.concatenate((a, b), axis=0)

def transponer(a):
    return a.T

In [ ]:
array1 = np.array([[0, 1, 2], 
            [9, 8, 5], 
            [-4, 2, 4]])

array2 = np.array([[0, 1, 2], 
            [3, 4, 5], 
            [6, 7, 8]])

operations = ['+', '-', '*', 'concat', 'transpose' ]
operations_ejemplo = ['&', '+', '-', '*', 'concat', 'transpose' ]

for operacion in operations_ejemplo:
    array_calculado = array_calculator(array1, array2, operacion)
    if isinstance(array_calculado, str):
        print(f'Operación no válida\nLista de operaciones disponibles: {operations}\n')
    else:
        print(f'Array1:\n{array1}\n Array2:\n{array2}\nOperación a realizar: {operacion}\nResultado:\n{array_calculado}\n')

Operación no válida
Lista de operaciones disponibles: ['+', '-', '*', 'concat', 'transpose']

Array1:
[[ 0  1  2]
 [ 9  8  5]
 [-4  2  4]]
 Array2:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Operación a realizar: +
Resultado:
[[ 0  2  4]
 [12 12 10]
 [ 2  9 12]]

Array1:
[[ 0  1  2]
 [ 9  8  5]
 [-4  2  4]]
 Array2:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Operación a realizar: -
Resultado:
[[  0   0   0]
 [  6   4   0]
 [-10  -5  -4]]

Array1:
[[ 0  1  2]
 [ 9  8  5]
 [-4  2  4]]
 Array2:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Operación a realizar: *
Resultado:
[[15 18 21]
 [54 76 98]
 [30 32 34]]

Array1:
[[ 0  1  2]
 [ 9  8  5]
 [-4  2  4]]
 Array2:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Operación a realizar: concat
Resultado:
[[ 0  1  2]
 [ 9  8  5]
 [-4  2  4]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]]

Array1:
[[ 0  1  2]
 [ 9  8  5]
 [-4  2  4]]
 Array2:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Operación a realizar: transpose
Resultado:
[[ 0  9 -4]
 [ 1  8  2]
 [ 2  5  4]]

